development: &default
  adapter: postgresql
  database: techlist_development
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: techlist_test

staging:
  <<: *default
  database: techlist_staging

production:
  <<: *default
  database: techlist_production
